### PR TITLE
Hydrogen's Love

### PR DESCRIPTION
**Pull request by goutameee**
Love Story for hydrogen. Actually, it's basic chemistry.

### CODE REVIEW

**Comment by goutameee** [comment]
This time I include my file

**Comment by lancejpollard** [comment]
[Looks pretty cool](https://github.com/goutameee/tune), sorry it autodeleted, I will try and prevent that next time. Thank you for being the first GitHub contributor!

**Comment by lancejpollard** [comment]
@goutameee I had some help coming up with simple names for the atoms, what do you think here? Then we can translate these!

> Hydrogen	Water Atom	"From the Greek words “hydro” and “genes.” Meaning “Water forming.” Water is the basic and most common part of hydrogen, hence its name “Water Atom.”"
Helium	Fiery Atom	"The word Helium is derived from the Greek sun god Helios, because it was first detected in the sun’s Corona. Hence the name “Fiery Atom.”"
Lithium	Earth Atom	"The word Lithium is gotten from the Greek word “Lithos.” Meaning stone. Now since lithium is found in a certain mineral in the Earth’s crust. It’s only fitting that it’s called “The Earth Atom.”"
Beryllium	Gemstone Atom	"Derived from a multi colored mineral used as sometimes as a gemstone."
Boron	Bone Atom	Because it is used for building strong bones, treating osteoarthritis.
Carbon	Life Atom	"Carbon is one of the most important chemical elements, but it is also capable of merging with other atoms to form substances called  compounds. Carbon compounds make up 18% of all matter in living things. So it’s safe to call it “The Life Atom.”"
Nitrogen	Booster Atom	"The word Nitrogen is gotten from two Greek words. “Nitron” and “genes.” Nitron meaning “Native soda,” and genes meaning “forming.” Nitrogen is responsible for  giving that extra boost to things like the light bulb industry, food industry, tire filling systems, e.t.c."
Oxygen	Air Atom	"Because it is the most useful element in Air. Highly  essential for life as well as a lot of other things on earth."
Fluorine	Rush Atom	Its Latin meaning is Flow and it is also used to treat tooth cavity, and also as a refrigerant, among other things. It’s fast and reliable, hence it’s name “The Rush Atom.”
Neon	The Red Atom	"Neon is commonly used in lights that are known as neon signs. It turns red in the vacuum tube."
Sodium	The Spice Atom	"From the English word “soda.” Also used in sodium compounds such as caustic soda, soda ash, and baking soda. So it’s safe to call it “The Spice Atom” since it’s a key ingredient in the compounds listed above."
Magnesium	The Ancient Atom	"Ore that attracts metals is commonly found in a place called Magnesia, which is the origin for words like magnet and magnetism as well as the chemical atom Magnesium. It is an ancient element common in that area, hence its name “The Ancient Atom.”"
Aluminum	The Vast Atom	"The word Aluminum is from the Latin word “Alum” which literally means “Bitter salt.” It is silver grey in color and is the twelfth most common element in the universe. Hence it’s name “The Vast Atom.”"
Silicon	"The Forger Atom"	"Silicon is derived from the Latin word “Silex” or “silicis” which both mean Flint, a kind of stone widely found in the earth’s crust. It is often mixed with silica sand and gravel to make concrete for walkways, foundation, and roads. Hence it’s name “The Forger Atom.”"
Phosphorous	Light Atom	"Derived from two Greek words “Phos” and “phoros.” Which both literally mean “Light Bearer.” White phosphorus emits a faint glow when exposed to oxygen, making it easily compactable with light."
Sulfur	The Burning Atom	"The Latin meaning of sulfur is “burn.” It is a chemical element that is abundant, multivalent, and nonmetallic in nature. It was referred to by the ancients as brimstone meaning “the burning stone.” "
Chlorine	The Pixie Atom	"Chlorine is a chemical element which is a yellow-green gas at room temperature. It can be called a “Pixie Atom” because of its color, which is almost like something out of a fantasy world. "
Argon	The Creeping Atom	"The Greek word for Argon means inactive, which literally means “slow,” because it undergoes almost no chemical reaction. Hence its name “The Creeping Atom,” because of its slow reacting nature."
Potassium (K)	Ash Atom	"The English name for the element potassium comes from the word potash, which refers to an early method of extracting salts by placing in a pot the ash of burnt wood, or tree leaves heating it, and evaporating the solution."
Calcium (Ca)	The Balance Atom	"Calcium is the most abundant metal and fifth most abundant element in the human body because it helps in the development of physiological and biochemical cells. In other words, it is very essential to the balance of the human body."
Scandium (Sc)	Rare Ore Atom	"Scandium is historically considered a rare earth metal. "
Titanium (Ti)	The pure Atom	"It is found in every white paint."
Vanadium (V)	The Mixer Atom	"Though it has many uses, its main function is to be used as a catalyst in many reactions as V205."
Chromium (Cr)	Magical color Atom	"As its meaning is color and it has many colors."
Manganese (Mn)	Shape shifter Atom	"It is second only to iron among the transition elements in its abundance in Earth’s crust; it is roughly similar to iron in its physical and chemical properties"
Iron (Fe)	Holy Metal Atom	"As it is the strongest and more abundant among all metals and its meaning is also Holy metal."
Cobalt (Co)	The Poison Atom	"As it is found in poisonous ores and was named by miners as toxic and poisonous. "
Nickel (Ni)	The Demon Atom	"Its Swedish meaning is Copper Demon as it highly resembles Copper both by function and structure."
Copper (Cu)	Flexible Atom	"As it is highly used in electrical appliances especially wires and motors."
Zinc(Zn)	Strength Atom	"Abundant in Vitamins."
Gallium (Ga)	Rooster Atom	"Its meaning in Latin is rooster."
Germanium (Ge)	"The Home Atom"	Its Latin meaning is Germany.
Arsenic (As)	The Manly Atom.	"Its meaning in Persian is Male. Plus, it is highly poisonous."
Selenium (Se)	Moon Atom.	"As the element is named after Selene, the Greek goddess of the moon."
Bromine (Br)	Stinky Atom.	"As its Greek meaning is dirt. Plus Bromine has a bad smell."
Krypton (Kr)	Hidden Atom	"Its meaning in Greek is hidden. Besides, it has colorless, odorless, tasteless, gaseous properties."
Rubidium (Rb)		"As its meaning in Latin is deepest red. It gives red light in the spectral line."
Strontium (Sr)	Firework Atom	It is best known for the brilliant reds its salts give to fireworks and flares
Yttrium (Y)	Red Atom	"It is used as the red color for early color television screens. It is also used in bulbs."
Zirconium (Zr)	The Gold Atom	"Its Persian meaning is Gold Like."
Niobium (Nb)	Snowy atom	"Its Greek meaning is snowy. It is also silver colored."
Molybdenum (Mo)	Two Faced Atom	"As its Greek translation is Lead Like. Molybdenum is often mistaken for lead which makes it a double faced kind of element. "
Technetium (Tc)	Man Forged Atom	"Because its Greek meaning is artificial and it was also produced artificially."
Ruthenium (Ru)	The Sluggish Atom 	"The name is derived from 'Ruthenia', the Latin name for Russia. Ruthenium is inert to most other chemicals. "
Rhodium (Rh)	Rose Atom	"The name is derived from the Greek 'rhodon', meaning rose colored."
Palladium (Pd)	The Wise Atom	"Palladium is named after the asteroid Pallas, in turn named after the Greek goddess of wisdom, Pallas."
Silver (Ag)	The Mirror Atom	"Its Akkadian meaning is to refine. It is used to make mirrors."
Cadmium (Cd)	Source Realm Atom	"80% of cadmium currently produced and used in rechargeable nickel-cadmium batteries, making it a source realm for batteries."
Indium (In)	The Phantom Atom 	"Greek word derived from Indigo. As it gives indigo color in spectral lines. And the word spectral means phantom or ghostly."
Tin (Sn)	The Cloak Atom	"As tin is used to coat other metals and prevent corrosion."
Antimony (Sb)	The Multiple Atom	"The name derives from the Greek 'anti - monos', meaning not alone."
Tellurium (Te)	Earth Realm Atom	"The name is derived from the Latin 'tellus', meaning Earth."
Iodine (I)Cerium (Ce)	Growth Atom	"Its Greek meaning is Violet, and it is very important for human body development."
Xenon (Xe)	Alien Atom	"From the Greek adjective (xenos): "foreign", "a stranger.”"
Caesium (Cs)	Blue Atom	"Its Latin meaning, Sky-Blue."
Barium (Ba)	Heavy Atom	"Its Latin meaning is heavy."
Lanthanum (La)	The Vanish Atom	"Its Greek meaning is hidden. It also vanishes as it contacts air."
Cerium (Ce)	Food Atom	"Its Latin meaning is Grain and it is named for the asteroid, Ceres, which in turn was named after the Roman goddess of agriculture."
Praseodymium (Pr)	The Twin Atom	"The name is derived from the Greek 'prasios didymos' meaning green twin."
Neodymium (Nd)	Magnet Atom	"The most important use for neodymium is in an alloy with iron and boron to make very strong permanent magnets."
Promethium (Pm)	Fire Atom	"Promethium is named after Prometheus of Greek mythology who stole fire from the Gods and gave it to humans. It is also used in lights and bulbs."
Samarium (Sm)	Alpha Magnet Atom	"Its magnets are much more powerful than iron magnets."
Europium (Eu)	The Homeland Atom	"Europium is named after Europe."
Gadolinium (Gd)	The Seeker Atom	"Its compounds are useful in magnetic resonance imaging (MRI), particularly in diagnosing cancerous tumors. In other words, it is used to scan for things that eat up the body."
Terbium (Tb)	Glow Atom	"It is used widely in devices like speakers, X ray machines and lightbulbs."
Dysprosium (Dy	Rare Atom	The name is derived from the Greek 'dysprositos', meaning hard to get.
Holmium (Ho)	The Scarce Atom	"The name is derived from the Latin name for Stockholm, 'Holmia'. It is also a rare earth metal."
Erbium (Er)	Glass Atom	"It is widely used in different types of glasses."
Thulium (Tm)	The Seeing Atom	"It produces X-ray in Nuclear reactors."
Ytterbium (Yb)	Thought Wielder Atom	"Mostly used in memory devices."
Lutetium (Lu)	The Swamp Atom	"The name is derived from the Latin word, 'Lutetia'. Gaulish for “place of mud.” And one of the synonyms for mud is “Swamp.”"
Hafnium (Hf)	The Stable Atom	"The name is derived from the Latin name for Copenhagen, which is the capital of Denmark. It is also a very stable element."
Tantalum (Ta)	Electric Atom	"One of the main uses of tantalum is in the production of electronic components. An oxide layer which forms on the surface of tantalum can act as an insulating (dielectric) layer making capacitors."
Tungsten (W)	Heavy Stone Atom	"The name is derived from the Swedish 'tung sten' meaning heavy stone."
Rhenium (Re)	River Atom	"The name is derived from the Latin name for the Rhine, 'Rhenus' which is a river."
Osmium (Os)	The Aroma Atom	"The name is derived from the Greek word 'osme', meaning smell."
Iridium (Ir)	The Rainbow Atom	"The name is derived from the Greek goddess of the rainbow, Iris."
Platinum (Pt)	 Small Silver Atom	"The name is derived from the Spanish 'platina', meaning little silver."
Gold (Au)	 Jewel Atom	"Its meaning in AngloSaxon is Bright Yellow. It is used extensively in jewelries."
Mercury (Hg)		Otherworldly Atom	Mercury is named after the planet, Mercury.
Thallium (Tl)	Twig Atom	"Thallium is derived from the Greek 'thallos', meaning a green twig. It also has bright-green spectral emission lines."
Lead (Pb)	Boogeyman Atom	"Lead is known to be detrimental to health, particularly that of children. Like a Boogeyman after the health of kids."
Bismuth (Bi)	Unchained Atom	"The name come from the German 'Bisemutum' a corruption of 'Weisse Masse' meaning white mass. It is also a free element, hence its name “The Unchained Atom.”"
Polonium (Po)	Shaky Atom	"Polonium is named after Poland, the native country of Marie Curie, who first isolated the element. It is also a rare and highly radioactive metal with unstable isotopes. "
Astatine (At)	Unstable Atom	The name comes from the Greek 'astatos', meaning unstable.
Radon (Rn)	Shiny Atom	"As it is highly radioactive and has the previous name niton which means shining."
Francium (Fr)	Loose Atom	"Francium is named after France. It is also rarely found in large bulks."
Radium (Ra)	Light Beam Atom	"The name is derived from the Latin 'radius', meaning ray."
Actinium (Ac)	Sparkle Atom	"From Greek (aktis/aktinos), which means "beam (ray).”"
Thorium (Th)	Thunder Atom	"Thorium is named after Thor, the Scandinavian god of Thunder."
Protactinium (Pa)	Decaying Atom	"The name is derived from the Greek 'protos', meaning first, as a prefix to the element actinium, which is produced through the radioactive decay of protactinium."
Uranium (U)	Power Atom	"Uranium was named after the planet Uranus. Uranium is a very important element because it provides us with nuclear fuel used to generate electricity in nuclear power stations."
Neptunium (Np)	Sea Atom	"Named after the planet Neptune. Neptune also means Roman god of the seas."
Plutonium (Pu)	Dead Atom	"Named after the planet Pluto. Pluto being the Greek god of the dead."
Americium (Am)	Free Atom	"Americium is named for America where it was first found. America being the land of the free gives it its name, “The Free Atom.”"
Curium (Cm)	Lady Atom	"Curium is named in honour of Pierre and Marie Curie."
Berkelium (Bk)	Vampire Atom	"Berkelium was named after the town Berkeley, California, where it was first made. It has a silvery-white color, something like that of a vampire dagger."
Californium (Cf)	Unveiled Atom	"Californium is named for the university and state of California, where the element was first made. It is also produced in large amounts that can be seen with the unaided eye, so it can be said to be “unveiled” since it was once hidden."
Einsteinium (Es)	Smart Atom	"Einsteinium is named after the renowned physicist Albert Einstein. Hence its name, “The Smart Atom.”"
Fermium (Fm)	Endangered Atom	"Fermium is named after the nuclear physicist Enrico Fermi. Francium is extremely rare. Hence, its name “Endangered Atom.” "
Mendelevium (Md)	Pioneer Atom	"Mendelevium is named for Dmitri Mendeleev who produced one of the first periodic tables. So it’s safe to call it “The Pioneer Atom.”"
Nobelium (No)	Crafted Atom	"Named in honour of Alfred Nobel, who invented dynamite and instituted the Nobel Prizes foundation. It can only be produced in a particle accelerator by bombarding lighter elements with charged particles. Hence its name, “Crafted Atom.”"
Lawrencium (Lr)	New Era Atom	"Lawrencium is named after Ernest O. Lawrence the inventor of the cyclotron."
Rutherfordium (Rf)	Hierarchy Atom	"Rutherfordium is named in honour of New Zealand Chemist Ernest Rutherford, one of the first to explain the structure of atoms."
Dubnium (Db)	Snow Atom	"Dubnium is named for the Russian town Dubna. Russia is also known as a heavy snow region."
Seaborgium (Sg)	Energy Atom	"Seaborgium is named for Glenn T. Seaborg, who was instrumental in producing several transuranium elements. Seaborgium has similarities to Uranium, hence its name “Energy Atom.”"
Bohrium (Bh)	Deep Atom	"Named in honor of Niels Bohr, who made fundamental contributions to the understanding of atomic structure and quantum mechanics. Because of this, it has enormous depth to its study. "
Hassium (Hs)	New Realm Atom	"The name is derived from the German state of Hesse where Hassium was first made. It was discovered in 1984, which makes it a new age atom. "
Meitnerium (Mt)	Merged Atom	"Named in honour of Lise Meitner, who shared discovery of nuclear fission."
Darmstadtium (Ds)	Newbirth Atom	"Darmstadtium is named after Darmstadt, Germany, where the element was first produced. It was created in 1994, and this makes it a recent discovery."
Roentgenium (Rg)	godseye Atom	"Named in honour of Wilhelm Conrad Röntgen, who discovered and produced X-rays. Its ability to function in an X-ray makes it an all seeing atom."
Copernicium (Cn)	Millennial Atom	"Copernicium is named for the Renaissance scientist Nicolaus Copernicus. It is aq"
Nihonium (Nh)	Danger Atom	"The name refers to the Japanese name for Japan. It is extremely radioactive."
Flerovium (Fl)	Uncertain Atom	"Named after the Russian physicist Georgy Flerov who founded the Joint Institute for Nuclear Research where the element was discovered. It is still a question whether it behaves more like a metal or Noble gas."
Moscovium (Mc)	Heart Atom	"The name refers to the Moscow region, where the Joint Institute of Nuclear Research is based. It is called a heart Atom because it was discovered in the heart of Russia."
Livermorium (Lv)	Mother Atom	"Named in honour of Lawrence Livermore National Laboratory, which collaborated in the discovery and is in Livermore. It is called the mother atom of flerovium."
Tennessine (Ts)	The Grand Atom	"The name refers to the US state of Tennessee. It is the second heaviest known element. "
Oganesson (Og)	Fused Atom	"The name recognises the Russian nuclear physicist Yuri Oganessian for his contributions to transactinide element research. It was formed by the joint efforts of Russian and American scientists."

**Comment by lancejpollard** [comment]
[Here's](https://github.com/drumworkteam/tune/commit/47fd205ad11ed3112210682358752660e7582fd0) an example of some things I do to get it ready.

**Comment by lancejpollard** [comment]
Almost to a final result:

> Hydrogen Water Atom "From the Greek words “hydro” and “genes.” Meaning “Water forming.” Water is the basic and most common part of hydrogen, hence its name “Water Atom.”"
Helium Sun Atom "The word Helium is derived from the Greek sun god Helios, because it was first detected in the sun’s Corona. Hence the name “Fiery Atom.”"
Lithium Stone Atom "The word Lithium is gotten from the Greek word “Lithos.” Meaning stone. Now since lithium is found in a certain mineral in the Earth’s crust. It’s only fitting that it’s called “The Earth Atom.”"
Beryllium Precious Atom "Derived from a multi colored mineral used as sometimes as a gemstone."
Boron Bone Atom Because it is used for building strong bones, treating osteoarthritis.
Carbon Life Atom "Carbon is one of the most important chemical elements, but it is also capable of merging with other atoms to form substances called compounds. Carbon compounds make up 18% of all matter in living things. So it’s safe to call it “The Life Atom.”"
Nitrogen Plant Atom "The word Nitrogen is gotten from two Greek words. “Nitron” and “genes.” Nitron meaning “Native soda,” and genes meaning “forming.” Nitrogen is responsible for giving that extra boost to things like the light bulb industry, food industry, tire filling systems, e.t.c."
Oxygen Breath Atom "Because it is the most useful element in Air. Highly essential for life as well as a lot of other things on earth."
Fluorine Tooth Atom Its Latin meaning is Flow and it is also used to treat tooth cavity, and also as a refrigerant, among other things. It’s fast and reliable, hence it’s name “The Rush Atom.”
Neon The Tube Atom "Neon is commonly used in lights that are known as neon signs. It turns red in the vacuum tube."
Sodium The Salt Atom "From the English word “soda.” Also used in sodium compounds such as caustic soda, soda ash, and baking soda. So it’s safe to call it “The Spice Atom” since it’s a key ingredient in the compounds listed above."
Magnesium The Ancient Atom "Ore that attracts metals is commonly found in a place called Magnesia, which is the origin for words like magnet and magnetism as well as the chemical atom Magnesium. It is an ancient element common in that area, hence its name “The Ancient Atom.”"
Aluminum The Shine Atom "The word Aluminum is from the Latin word “Alum” which literally means “Bitter salt.” It is silver grey in color and is the twelfth most common element in the universe. Hence it’s name “The Vast Atom.”"
Silicon "The Sand Atom" "Silicon is derived from the Latin word “Silex” or “silicis” which both mean Flint, a kind of stone widely found in the earth’s crust. It is often mixed with silica sand and gravel to make concrete for walkways, foundation, and roads. Hence it’s name “The Forger Atom.”"
Phosphorous Light Atom "Derived from two Greek words “Phos” and “phoros.” Which both literally mean “Light Bearer.” White phosphorus emits a faint glow when exposed to oxygen, making it easily compactable with light."
Sulfur The Stank Atom "The Latin meaning of sulfur is “burn.” It is a chemical element that is abundant, multivalent, and nonmetallic in nature. It was referred to by the ancients as brimstone meaning “the burning stone.” "
Chlorine The Green Atom "Chlorine is a chemical element which is a yellow-green gas at room temperature. It can be called a “Pixie Atom” because of its color, which is almost like something out of a fantasy world. "
Argon The Slow Atom "The Greek word for Argon means inactive, which literally means “slow,” because it undergoes almost no chemical reaction. Hence its name “The Creeping Atom,” because of its slow reacting nature."
Potassium (K) Ash Atom "The English name for the element potassium comes from the word potash, which refers to an early method of extracting salts by placing in a pot the ash of burnt wood, or tree leaves heating it, and evaporating the solution."
Calcium (Ca) The Nerve Atom "Calcium is the most abundant metal and fifth most abundant element in the human body because it helps in the development of physiological and biochemical cells. In other words, it is very essential to the balance of the human body."
Scandium (Sc) Soft Atom "Scandium is historically considered a rare earth metal. "
Titanium (Ti) The Strength Atom "It is found in every white paint."
Vanadium (V) The Beauty Atom "Though it has many uses, its main function is to be used as a catalyst in many reactions as V205."
Chromium (Cr) Color Atom "As its meaning is color and it has many colors."
Manganese (Mn) Magnificent Atom "It is second only to iron among the transition elements in its abundance in Earth’s crust; it is roughly similar to iron in its physical and chemical properties"
Iron (Fe) Metal Atom "As it is the strongest and more abundant among all metals and its meaning is also Holy metal."
Cobalt (Co) The Ring Atom "As it is found in poisonous ores and was named by miners as toxic and poisonous. "
Nickel (Ni) The White Atom "Its Swedish meaning is Copper Demon as it highly resembles Copper both by function and structure."
Copper (Cu) Message Atom "As it is highly used in electrical appliances especially wires and motors."
Zinc(Zn) The Brittle Atom "Abundant in Vitamins."
Gallium (Ga) Bird Atom "Its meaning in Latin is rooster."
Germanium (Ge) "The Cave Atom" Its Latin meaning is Germany.
Arsenic (As) The Poison Atom. "Its meaning in Persian is Male. Plus, it is highly poisonous."
Selenium (Se) Moon Atom. "As the element is named after Selene, the Greek goddess of the moon."
Bromine (Br) Ocean Atom. "As its Greek meaning is dirt. Plus Bromine has a bad smell."
Krypton (Kr) Hidden Atom "Its meaning in Greek is hidden. Besides, it has colorless, odorless, tasteless, gaseous properties."
Rubidium (Rb) Red Atom "As its meaning in Latin is deepest red. It gives red light in the spectral line."
Strontium (Sr) Burst Atom It is best known for the brilliant reds its salts give to fireworks and flares
Yttrium (Y) Bulb Atom "It is used as the red color for early color television screens. It is also used in bulbs."
Zirconium (Zr) The Opaque Atom "Its Persian meaning is Gold Like."
Niobium (Nb) Snowy atom "Its Greek meaning is snowy. It is also silver colored."
Molybdenum (Mo) Dark Atom "As its Greek translation is Lead Like. Molybdenum is often mistaken for lead which makes it a double faced kind of element. "
Technetium (Tc) Synthetic Atom "Because its Greek meaning is artificial and it was also produced artificially."
Ruthenium (Ru) The Still Atom "The name is derived from 'Ruthenia', the Latin name for Russia. Ruthenium is inert to most other chemicals. "
Rhodium (Rh) Rose Atom "The name is derived from the Greek 'rhodon', meaning rose colored."
Palladium (Pd) The Wise Atom "Palladium is named after the asteroid Pallas, in turn named after the Greek goddess of wisdom, Pallas."
Silver (Ag) The Mirror Atom "Its Akkadian meaning is to refine. It is used to make mirrors."
Cadmium (Cd) Source Atom "80% of cadmium currently produced and used in rechargeable nickel-cadmium batteries, making it a source realm for batteries."
Indium (In) The Ghost Atom "Greek word derived from Indigo. As it gives indigo color in spectral lines. And the word spectral means phantom or ghostly."
Tin (Sn) The Cloak Atom "As tin is used to coat other metals and prevent corrosion."
Antimony (Sb) The Paint Atom "The name derives from the Greek 'anti - monos', meaning not alone."
Tellurium (Te) Earth Atom "The name is derived from the Latin 'tellus', meaning Earth."
Iodine (I)Cerium (Ce) Blood Atom "Its Greek meaning is Violet, and it is very important for human body development."
Xenon (Xe) Alien Atom "From the Greek adjective (xenos): "foreign", "a stranger.”"
Caesium (Cs) Sky Atom "Its Latin meaning, Sky-Blue."
Barium (Ba) Heavy Atom "Its Latin meaning is heavy."
Lanthanum (La) The Air Atom "Its Greek meaning is hidden. It also vanishes as it contacts air."
Cerium (Ce) Food Atom "Its Latin meaning is Grain and it is named for the asteroid, Ceres, which in turn was named after the Roman goddess of agriculture."
Praseodymium (Pr) The Wind Atom "The name is derived from the Greek 'prasios didymos' meaning green twin."
Neodymium (Nd) Magnet Atom "The most important use for neodymium is in an alloy with iron and boron to make very strong permanent magnets."
Promethium (Pm) Fire Atom "Promethium is named after Prometheus of Greek mythology who stole fire from the Gods and gave it to humans. It is also used in lights and bulbs."
Samarium (Sm) Power Atom "Its magnets are much more powerful than iron magnets."
Europium (Eu) The Screen Atom "Europium is named after Europe."
Gadolinium (Gd) The Seeker Atom "Its compounds are useful in magnetic resonance imaging (MRI), particularly in diagnosing cancerous tumors. In other words, it is used to scan for things that eat up the body."
Terbium (Tb) Glow Atom "It is used widely in devices like speakers, X ray machines and lightbulbs."
Dysprosium (Dy Difficult Atom The name is derived from the Greek 'dysprositos', meaning hard to get.
Holmium (Ho) The Permeable Atom "The name is derived from the Latin name for Stockholm, 'Holmia'. It is also a rare earth metal."
Erbium (Er) Glass Atom "It is widely used in different types of glasses."
Thulium (Tm) The Beyond Atom "It produces X-ray in Nuclear reactors."
Ytterbium (Yb) Memory Atom "Mostly used in memory devices."
Lutetium (Lu) The Swamp Atom "The name is derived from the Latin word, 'Lutetia'. Gaulish for “place of mud.” And one of the synonyms for mud is “Swamp.”"
Hafnium (Hf) The Tool Atom "The name is derived from the Latin name for Copenhagen, which is the capital of Denmark. It is also a very stable element."
Tantalum (Ta) Electric Atom "One of the main uses of tantalum is in the production of electronic components. An oxide layer which forms on the surface of tantalum can act as an insulating (dielectric) layer making capacitors."
Tungsten (W) Wolf Atom "The name is derived from the Swedish 'tung sten' meaning heavy stone."
Rhenium (Re) River Atom "The name is derived from the Latin name for the Rhine, 'Rhenus' which is a river."
Osmium (Os) The Wing Atom "The name is derived from the Greek word 'osme', meaning smell."
Iridium (Ir) The Rainbow Atom "The name is derived from the Greek goddess of the rainbow, Iris."
Platinum (Pt) Vibrant Atom "The name is derived from the Spanish 'platina', meaning little silver."
Gold (Au) Crown Atom "Its meaning in AngloSaxon is Bright Yellow. It is used extensively in jewelries."
Mercury (Hg) Liquid Atom Mercury is named after the planet, Mercury.
Thallium (Tl) Stick Atom "Thallium is derived from the Greek 'thallos', meaning a green twig. It also has bright-green spectral emission lines."
Lead (Pb) Death Atom "Lead is known to be detrimental to health, particularly that of children. Like a Boogeyman after the health of kids."
Bismuth (Bi) Shadow Atom "The name come from the German 'Bisemutum' a corruption of 'Weisse Masse' meaning white mass. It is also a free element, hence its name “The Unchained Atom.”"
Polonium (Po) Shaky Atom "Polonium is named after Poland, the native country of Marie Curie, who first isolated the element. It is also a rare and highly radioactive metal with unstable isotopes. "
Astatine (At) Quick Atom The name comes from the Greek 'astatos', meaning unstable.
Radon (Rn) Trace Atom "As it is highly radioactive and has the previous name niton which means shining."
Francium (Fr) Loose Atom "Francium is named after France. It is also rarely found in large bulks."
Radium (Ra) Beam Atom "The name is derived from the Latin 'radius', meaning ray."
Actinium (Ac) Sparkle Atom "From Greek (aktis/aktinos), which means "beam (ray).”"
Thorium (Th) Thunder Atom "Thorium is named after Thor, the Scandinavian god of Thunder."
Protactinium (Pa) Sealed Atom "The name is derived from the Greek 'protos', meaning first, as a prefix to the element actinium, which is produced through the radioactive decay of protactinium."
Uranium (U) Destruction Atom "Uranium was named after the planet Uranus. Uranium is a very important element because it provides us with nuclear fuel used to generate electricity in nuclear power stations."
Neptunium (Np) Wash Atom "Named after the planet Neptune. Neptune also means Roman god of the seas."
Plutonium (Pu) Far Atom "Named after the planet Pluto. Pluto being the Greek god of the dead."
Americium (Am) Smoke Atom "Americium is named for America where it was first found. America being the land of the free gives it its name, “The Free Atom.”"
Curium (Cm) Female Atom "Curium is named in honour of Pierre and Marie Curie."
Berkelium (Bk) Vampire Atom "Berkelium was named after the town Berkeley, California, where it was first made. It has a silvery-white color, something like that of a vampire dagger."
Californium (Cf) Naked Atom "Californium is named for the university and state of California, where the element was first made. It is also produced in large amounts that can be seen with the unaided eye, so it can be said to be “unveiled” since it was once hidden."
Einsteinium (Es) Smart Atom "Einsteinium is named after the renowned physicist Albert Einstein. Hence its name, “The Smart Atom.”"
Fermium (Fm) Rare Atom "Fermium is named after the nuclear physicist Enrico Fermi. Francium is extremely rare. Hence, its name “Endangered Atom.” "
Mendelevium (Md) Pioneer Atom "Mendelevium is named for Dmitri Mendeleev who produced one of the first periodic tables. So it’s safe to call it “The Pioneer Atom.”"
Nobelium (No) Prize Atom "Named in honour of Alfred Nobel, who invented dynamite and instituted the Nobel Prizes foundation. It can only be produced in a particle accelerator by bombarding lighter elements with charged particles. Hence its name, “Crafted Atom.”"
Lawrencium (Lr) Open Atom "Lawrencium is named after Ernest O. Lawrence the inventor of the cyclotron."
Rutherfordium (Rf) Structure Atom "Rutherfordium is named in honour of New Zealand Chemist Ernest Rutherford, one of the first to explain the structure of atoms."
Dubnium (Db) Race Atom "Dubnium is named for the Russian town Dubna. Russia is also known as a heavy snow region."
Seaborgium (Sg) Energy Atom "Seaborgium is named for Glenn T. Seaborg, who was instrumental in producing several transuranium elements. Seaborgium has similarities to Uranium, hence its name “Energy Atom.”"
Bohrium (Bh) Deep Atom "Named in honor of Niels Bohr, who made fundamental contributions to the understanding of atomic structure and quantum mechanics. Because of this, it has enormous depth to its study. "
Hassium (Hs) New Realm Atom "The name is derived from the German state of Hesse where Hassium was first made. It was discovered in 1984, which makes it a new age atom. "
Meitnerium (Mt) Merged Atom "Named in honour of Lise Meitner, who shared discovery of nuclear fission."
Darmstadtium (Ds) Newbirth Atom "Darmstadtium is named after Darmstadt, Germany, where the element was first produced. It was created in 1994, and this makes it a recent discovery."
Roentgenium (Rg) godseye Atom "Named in honour of Wilhelm Conrad Röntgen, who discovered and produced X-rays. Its ability to function in an X-ray makes it an all seeing atom."
Copernicium (Cn) Millennial Atom "Copernicium is named for the Renaissance scientist Nicolaus Copernicus. It is aq"
Nihonium (Nh) Danger Atom "The name refers to the Japanese name for Japan. It is extremely radioactive."
Flerovium (Fl) Uncertain Atom "Named after the Russian physicist Georgy Flerov who founded the Joint Institute for Nuclear Research where the element was discovered. It is still a question whether it behaves more like a metal or Noble gas."
Moscovium (Mc) Heart Atom "The name refers to the Moscow region, where the Joint Institute of Nuclear Research is based. It is called a heart Atom because it was discovered in the heart of Russia."
Livermorium (Lv) Mother Atom "Named in honour of Lawrence Livermore National Laboratory, which collaborated in the discovery and is in Livermore. It is called the mother atom of flerovium."
Tennessine (Ts) The Grand Atom "The name refers to the US state of Tennessee. It is the second heaviest known element. "
Oganesson (Og) Fused Atom "The name recognises the Russian nuclear physicist Yuri Oganessian for his contributions to transactinide element research. It was formed by the joint efforts of Russian and American scientists."

**Pull request closed without merging**
